<?php

$lang = array();
$lang['DESCR'] = 'Rekanji is a site for Japanese language learners. You see a random list of kanji. Do you remember this character? Check yourself by tapping it. Register to access all kanji. There are no ads or spam here.';
$lang['RESET_PASSWORD'] = 'reset password';
$lang['TRY_IT'] = 'Try it';
$lang['GO_BACK'] = 'Back';
$lang['WHAT_IS'] = "What's this?";
$lang['ENTER_EMAIL'] = 'Please enter your email';
$lang['ENTER_PASS'] = 'Please enter your password';
$lang['QUERY_FAIL'] = 'Database error';
$lang['LOGIN_NOWAY'] ='Sorry, cannot log in. Perhaps your account is not activated or the username / password are incorrect.';
$lang['LOGIN_TITLE'] = 'log in';
$lang['LOGIN_YOURNAME'] = 'Name ';
$lang['LOGIN_YOURPASS'] = 'password ';
$lang['LOGIN_OK'] = 'log in';
$lang['GO_REGISTER'] = 'register';
$lang['THIS_ON'] = 'on`yomi';
$lang['THIS_KUN'] = 'kun`yomi';
$lang['TRANSLATES'] = 'meaning';
$lang['YESS'] = 'I remember';
$lang['NOPE'] = 'I don`t';
$lang['ABOUT_DIV'] = '<div id="aboutDiv" onclick="about();" size="+1">
		<h3>ReKanji: Remember Kanji.</h3><br/>
		This kanji learning aid allows you to:<br/>
		<ul>
		<li>check your knowledge</li>
		<li>make a list of kanji you know</li>
		<li>make a list of kanji to learn</li>
		<li>watch your progress</li>
		</ul>
		<br/>
		You see a random collection of characters taken from the Standard Kanji List (常用漢字). 
		Find the characters that you are familiar with or that you like. Click them and check yourself: 
		do you remember the readings right? If you do, click "I remember". If not, click "I don`t". 
		To save your progress and exit, press "Save and quit". To clear the progress and start over, press "Clear everything". 
		To "forget" a marked character, click it again.<br/>
		Use the Mode button to change between (1) all characters, (2) only those you are going to learn and (3) only those you remember.
		<br/>
                The font used in the logo: Lack by Adrien Midzic, <a href="http://velvetyne.fr/fonts/lack">
                http://velvetyne.fr/fonts/lack</a>
                <br/>
                
		<div align="right">Daniel</div>';
$lang['NOIE']='Sorry, Microsoft Internet Explorer may not display the page correctly.';
$lang['DB_ERROR']="Sorry, a database error has occurred.n";
$lang['ACTIVATION_LINK']="Hello, this message has been automatically generated by ReKanji.com." .
"If you are not going to register at ReKanji.com, please ignore this message. n Your activation link:n";
$lang['MESSAGE_TITLE']='ReKanji Registration';
$lang['CHECK_YOURMAIL'] = 'Thank you! The activation link has been sent to the following address: ';
$lang['ERROR'] = 'Sorry, an error has occurred.';
$lang['EMAIL_OR_NAME_USED'] = 'These email or name are already in use.'; 
$lang['REG_TITLE'] = 'Registration';
$lang['LOGIN'] = 'Log in';
$lang['ACTIVATION'] = 'Activation';
$lang['YOU_SURE'] = 'All the progress will be abandoned! Are you sure?';
$lang['MODE']='Mode ';
$lang['CLEAR']='Clear everything';
$lang['SAVE_QUIT']='Save and quit';
$lang['ABOUT']='About';
$lang['ACCOUNT_READY']='Your account is ready.';
$lang['FORGOT_PASSWORD']='reset password';
$lang['NO_EMAIL']='Sorry, this email is not registered.';
$lang['FORGOT_LINK']='Please use this link to restore your password at rekanji.com: ';
$lang['CHECK_FORGOT']='To proceed with restoring the password please check your mail : ';
$lang['NEW_PASS']='Please enter a new password';
?>


    
    

    
    
    
    
    
    
    
    